### ISSUE TITLE
Customisations don't appear on the post-logout login page

### ISSUE THREAD

**Issue by mjnewton** [marneu/login_info#1]
Customisations (custom_login_info_before, custom_login_bottomline, custom_login_info_after) work as expected on the login screen however when you log out they do not appear on the login screen presented. An F5 refresh does however cause the customisations to then appear.

**Comment by marneu** [comment]
Have you tried clearing your browser cache?

**Comment by mjnewton** [comment]
Hi Marcus,

No joy with a cache clear, and I can reproduce with an unused browser.

If it helps, some screenshots may illustrate the behaviour being witnessed:

[http://www.newtonnet.co.uk/temp/Pre-login Login Screen.png](url)
[http://www.newtonnet.co.uk/temp/Post-logout Login Screen.png](url)
[http://www.newtonnet.co.uk/temp/Post-F5-after-logout Login Screen.png](url)

**Comment by marneu** [comment]
Looks like a redirect after logout to the basic webmail page would make sense.
I can try to make some tests within the upcoming week.

**Comment by mjnewton** [comment]
That would be great! Thank you!

**Comment by mjnewton** [comment]
I stumbled across your [logout_redirect](https://github.com/marneu/logout_redirect) plugin and that has solved the issue although I imagine it might not work for everyone as the dynamic URL redirect can only be based on the domain portion of a user's mailbox. It works for me though as all users use a URL of https://mail.<domain> where <domain> always matches the user's e-mail address.

**Comment by marneu** [comment]
That's the best solution as I mentioned before, as any parameters get stripped off.
If your users share one email domain, you can fix the redirect url within "logout_redirect"
to a fixed value.
`$config['logout_redirect_url'] = 'http://mail.<your_domain>/<your parameters optional>';`
Where <your domain> is the real domain you want to redirect to. If the parameter has no "%d", nothing will be replaced.

**Comment by mjnewton** [comment]
Yes, in my case whilst there are a variety of domains in use they each have their own `https://mail.<domain>` URL that matches their domain.
