### ISSUE TITLE
Login Info after not shown

### ISSUE THREAD

**Issue by xge** [marneu/login_info#4]
When setting `custom_login_info_before` to `false` `custom_login_info_after` will not be printed and Chrome console prints an exception:

```
Uncaught ReferenceError: login_info_before is not defined
    at login_info.js?s=1487524259:13
```

Same applies to `custom_login_bottomline` if `custom_login_(before|after)` are set to `false`.

**Workaround:** set the variables you don't need to an empty string:

```php
$rcmail_config['custom_login_info_before'] = ' ';
```

**Comment by marneu** [comment]
should be fixed in login_info.js
