### ISSUE TITLE
Task also logout

### ISSUE THREAD

**Issue by Skygge666** [marneu/login_info#5]
Please change $task 
to
public $task = 'login|logout';
to make the info visible also on the logout page. Regards!

**Comment by marneu** [comment]
You may want to have a look at https://github.com/marneu/logout_redirect which is thought to do stuff in the logout situation - probably redirect to login page again.
This addl. info at the login point is meant for information that the user needs to know before logging in.
I would like to keep this granularity and not to mix up functions, does this information solve your question?
