### ISSUE TITLE
Automatic linking does not work for license string in composer.json

### ISSUE THREAD

**Issue by lrupp** [marneu/login_info#7]
The current license string in the composer.json field contains:
`"license": "GNU GPLv3+"`
this results in a plain text field if a user clicks on the "about" button in Roundcubemail. 

If the string is changed to:
`"license": "GPLv3+"`
instead, the WebUI automatically renders this into a link, pointing to the correct license at the [GNU homepage](http://www.gnu.org/licenses/gpl-3.0.html).

**Comment by marneu** [comment]
Thanks for letting me know. Correction accepted.
